name: genie_coder_monorepo
repository: https://github.com/GenieCoderSrc/genie_coder_monorepo
packages:
  - packages/*

command:
  version:
    linkToCommits: true
    updateGitTagRefs: true
    includeCommitId: true
    updateDependents: true
    dependents:
      update: true
    conventionalCommits: true       # 🚀 Enables changelog generation
    changelog:                       # 🚀 Per-package changelog
      entryFile: CHANGELOG.md
      includeCommits: true
  bootstrap:
    runPubGetInParallel: true
    usePubspecOverrides: true


scripts:
  analyze:
    run: flutter analyze
  format:
    run: dart format .
  test:
    run: flutter test --coverage
    select-package:
      dir-exists: test
      file-exists: pubspec.yaml
      depends-on: flutter_test




