name: genie_coder_monorepo
repository: https://github.com/GenieCoderSrc/genie_coder_monorepo
packages:
  - packages/*

command:
  version:
    linkToCommits: true
    updateGitTagRefs: true
    workspaceChangelog: false

  bootstrap:
    runPubGetInParallel: true



scripts:
  analyze:
    run: flutter analyze
  format:
    run: dart format .
  test:
    run: flutter test --coverage





