name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'


      - name: Activate Melos globally
        run: flutter pub global activate melos

      - name: Bootstrap packages
        run: flutter pub global run melos bootstrap

      - name: Version packages
        run: flutter pub global run melos version --yes

      - name: Publish packages
        run: flutter pub global run melos publish --yes
        env:
          PUB_CREDENTIALS: ${{ secrets.MONO_REPO_PAT }}
