name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Activate Melos
        run: dart pub global activate melos

      - name: Bootstrap Packages
        run: melos bootstrap

      - name: Version Packages
        run: melos version --yes

      - name: Publish Packages
        run: melos publish --yes
        env:
          PUB_CREDENTIALS: ${{ secrets.GH_PAT }}

